version: '3'

services:
  db:
    image: postgres:15.1-alpine
    container_name: track-time-db
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=track-time
    ports:
      - "5435:5432"