spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/track-time
    username: egorov
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /tracking-system-documentation
  api-docs:
    path: /tracking-system-api-docs